---
title: "R Notebook"
output: html_notebook
---

# Installing packages 

```{r}
#install.packages("rio")
library("rio")
library("dplyr")
```

# Loading CSV file 

```{r}
df <- rio::import("met_useofforce_2020.csv")
```
# Selecting columns of relevance 

```{r}
newdf = select(df, IncidentDate:PrimaryConduct, SubjectAge:MentalDisability)
```

# Finding duplicated entries

```{r}
newdf2 <- newdf %>%
  group_by(IncidentDate, IncidentTime, `Incident Location: Street/Highway`, `Incident Location: Public Transport`, `Incident Location: Retail Premises`, `Incident Location: Open ground (e.g. park, car park, field)`, `Incident Location: Licensed Premises`, `Incident Location: Sports or Event Stadia`, `Incident Location: Hospital/A&E (non-mental-health setting)`, `Incident Location: Mental Health Setting`, `Incident Location: Police vehicle with prisoner handling cage`, `Incident Location: Police vehicle without prisoner handling cage`, `Incident Location: Dwelling`, `Incident Location: Police station (excluding custody block)`, `Incident Location: Custody Block`, `Incident Location: Ambulance`, `Incident Location: Other`, Borough, SubjectAge, SubjectEthnicity, SubjectGender, PhysicalDisability, MentalDisability) %>%
  mutate(num_dups=n(),
         dup_id=row_number()) %>%
  ungroup() %>%
  mutate(is_duplicated=dup_id>1)
```

# Filter duplicated entries 

```{r}
filterdf <- newdf2 %>% filter(is_duplicated==FALSE)
```

# Counting subject ethnicitiy 

```{r}
dataframe <- filterdf %>% count(SubjectEthnicity)
```
# Counting use of force by borough 

```{r}
dataframe2 <- filterdf %>% count(Borough)
```

```{r}
write.table(dataframe, file="Met2020ethn.csv", sep=",")
```

```{r}
write.table(dataframe2, file="Met2020borough.csv", sep=",")
```

